/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicFooter: typeof import('./src/components/BasicFooter.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    KojEditor: typeof import('./src/components/KojEditor.vue')['default']
    MainBanner: typeof import('./src/components/MainBanner.vue')['default']
    ManagerNav: typeof import('./src/components/ManagerNav.vue')['default']
    Mannagernav: typeof import('./src/components/Mannagernav.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor.vue')['default']
    MdViewer: typeof import('./src/components/MdViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMainBanner: typeof import('./src/components/UserMainBanner.vue')['default']
    UserNav: typeof import('./src/components/UserNav.vue')['default']
  }
}
